apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-route
  namespace: banking
spec:
  hosts:
  - "*" # interpreted as reviews.foo.svc.cluster.local
  gateways:
  - default/bnk-gateway  
  http:
  - match:
    - uri:
        prefix: "/customer/"
    rewrite:
      uri: "/api/"                  
    route:
    - destination:
        host: customers-apis-common.banking.svc.cluster.local # interpreted as reviews.foo.svc.cluster.local
        port:
          number: 80                  

