apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: transfers-route
  namespace: banking
spec:
  hosts:
  - "*"
  gateways:
  - default/bnk-gateway  
  http:
  - match:
    - uri:
        prefix: "/account/"
    rewrite:
      uri: "/api/"                  
    route:
    - destination:
        host: transfers-transfers-api.banking.svc.cluster.local 
        port:
          number: 80                  

