# replicaCount: 1
# clusterName: bnk-cluster

# image:
#   repository: ""
#   tag: "sometag"
#   pullPolicy: IfNotPresent

# service:
#   type: ClusterIP
#   port: 80

# ingress:
#   enabled: false

# resources: 
#   limits:
#     cpu: 100m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 256Mi

# autoscaling:
#   enabled: true
#   minReplicas: 1
#   maxReplicas: 1
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}

# serviceAccount:
#   create: true
#   annotations: {}
#   name: ""
  
# env: {}   

      